Use mini_project;
DROP TABLE IF EXISTS Accident_Subset;
Create External Table Accident_Subset (STATE INT, ST_CASE INT, VE_TOTAL INT, VE_FORMS INT, PVH_INVL INT, PEDS INT,
PERNOTMVIT INT, PERMVIT INT, PERSONS INT, COUNTY INT, CITY INT, DAY INT, MONTH INT, YEAR INT, DAY_WEEK INT, HOUR INT, MINUTE INT,
NHS INT, RUR_URB INT, FUNC_SYS INT, RD_OWNER INT, ROUTE INT, TWAY_ID VARCHAR(30), TWAY_ID2 VARCHAR(30), MILEPT INT, SP_JUR INT, HARM_EV INT,
MAN_COLL INT, RELJCT1 INT, RELJCT2 INT, TYP_INT INT, WRK_ZONE INT, REL_ROAD INT, LGT_COND INT, WEATHER1 INT, WEATHER2 INT, WEATHER INT, SCH_BUS INT,
RAIL VARCHAR(7), NOT_HOUR INT, NOT_MIN INT, ARR_HOUR INT, ARR_MIN INT, HOSP_HR INT, HOSP_MN INT, CF1 INT, CF2 INT, CF3 INT, FATALS INT, DRUNK_DR INT,
LATITUDE INT, LONGITUDE INT, zipcode varchar(50))
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/user/admin/Landing_dir/Accident_Subset';
